article/article/articles_app/urls.py
from django.urls import path

from article.articles_app.views import ArticlesListView, ArticleCreateView, SourceCreateView, SourceDetailsView, SourcesListView

urlpatterns = (
    path('', ArticlesListView.as_view(), name='index'),
    path('articles/create/', ArticleCreateView.as_view(), name='create article'),
    path('sources/', SourcesListView.as_view(), name='list sources'),
    path('sources/<int:pk>', SourceDetailsView.as_view(), name='details source'),
    path('source/create/', SourceCreateView.as_view(), name='create source'),
)

article/article/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('article.articles_app.urls')),
]

article/article/articles_app/models.py
from django.db import models


class Source(models.Model):
    name = models.CharField(
        max_length=50,
    )

    url = models.URLField(
        max_length=200,
    )

    def __str__(self):
        return self.name


class Article(models.Model):
    title = models.CharField(
        max_length=100,
    )

    description = models.TextField()

    image_url = models.URLField(
        max_length=200,
    )

    source = models.ForeignKey(
        Source,
        on_delete=models.CASCADE,
    )

article/article/articles_app/views.py
from django.urls import reverse_lazy, reverse
from django.views import generic as views
from django.views.generic.detail import SingleObjectMixin

from article.articles_app.models import Article, Source


class ArticleCreateView(views.CreateView):
    model = Article
    template_name = 'articles_app/create-article.html'
    success_url = reverse_lazy('index')
    fields = '__all__'


class SourceCreateView(views.CreateView):
    model = Source
    template_name = 'articles_app/create-source.html'
    # success_url = reverse_lazy('index')
    fields = '__all__'

    def get_success_url(self):
        return reverse('details source', kwargs={
            'pk': self.object.id,
        })


class ArticlesListView(views.ListView):
    model = Article
    template_name = 'articles_app/list-articles.html'
    # context_object_name = 'articles'


class SourceDetailsView(SingleObjectMixin, views.ListView):
    model = Source
    template_name = 'articles_app/details-source.html'
    object = None
    paginate_by = 3

    def get(self, request, *args, **kwargs):
        self.object = self.get_object(queryset=Source.objects.all())
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['source'] = self.object
        return context

    def get_queryset(self):
        return self.object.article_set.all()


class SourcesListView(views.ListView):
    model = Source
    template_name = 'articles_app/list-sources.html'

article/templates/articles_app/create-article.html
{% extends 'shared/base.html' %}
{% block content %}

    <div class="article-create-section">
        <div class="article-create-container container">
            <h1>Create a new Article</h1>
            <form method="post" action="{% url 'create article' %}">
                {% csrf_token %}
                {{ form }}
                <input class="btn" type="submit" value="Create Article">
            </form>
        </div>
    </div>

{% endblock %}

article/templates/articles_app/create-source.html
{% extends 'shared/base.html' %}
{% block content %}

    <div class="source-create-section">
        <div class="source-create-container container">
            <h1>Create a new Source</h1>
            <form method="post" action="{% url 'create source' %}">
                {% csrf_token %}
                {{ form }}
                <input class="btn" type="submit" value="Create Source">
            </form>
        </div>
    </div>

{% endblock %}

article/templates/articles_app/details-source.html
{% extends 'shared/base.html' %}
{% block content %}

    <div class="source-details-section">
        <div class="source-details-container container">
            <h2>Source: {{ source.name }}</h2>
            <ol>

                {% for article in page_obj.object_list %}
                    <div class="article-card">
                        <h3 class="article-title small">{{ article.title }}</h3>
                        <img class="article-image large"
                             src="{{ article.image_url }}">
                        <p>{{ article.description }}</p>
                        <span class="source">{{ source.name }}</span>
                    </div>
                {% endfor %}

            </ol>
            <div class="pagination">
                {% if page_obj.has_previous %}
                    <a href="?page={{ page_obj.previous_page_number }}">prev</a>
                {% else %}
                    <a href="/" style="pointer-events: none" >prev</a>
                {% endif %}
                <span class="current">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
                    </span>
                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">next</a>
                {% else %}
                    <a href="/" style="pointer-events: none">next</a>
                {% endif %}
            </div>
        </div>
    </div>

{% endblock %}

article/templates/articles_app/list-articles.html
{% extends 'shared/base.html' %}
{% block content %}

    <div class="home-page-section">
        <div class="home-page-container container">
            {% for article in article_list %}
                <div class="article-card">
                    <h1 class="article-title">{{ article.title}}</h1>
                    <img class="article-image" src="{{ article.image_url }}">
                    <p>{{ article.description}}</p>
                    <span class="source">{{ article.source.name }}</span>
                </div>
            {% endfor %}

        </div>
    </div>

{% endblock %}

article/templates/articles_app/list-sources.html
{% extends 'shared/base.html' %}
{% block content %}

    <div class="source-list-section">
        <div class="source-list-container container">
            <h2>All Sources</h2>

            {% for source in source_list %}
                <div class="source-item-card">
                    <h3>{{ source.name }}</h3>
                    <a href="{% url 'details source' source.id %}">See related articles</a>
                    <p>Link: <a href="{{ source.url }}" target="_blank">{{ source.name }}</a></p>
                </div>
            {% endfor %}

        </div>
    </div>

{% endblock %}

article/templates/shared/base.html
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
    <title>News</title>
</head>

<body>
<div class="navigation-section">
    <nav class="navigation-container container">
        <a class="link-item" href="{% url 'index' %}">Home Page</a>
        <a class="link-item" href="{% url 'list sources' %}">Sources</a>
        <a class="link-item" href="{% url 'create source' %}">Add new Source</a>
        <a class="link-item" href="{% url 'create article' %}">Add new Article</a>
    </nav>
</div>

{% block content %}
{% endblock %}

</body>
</html>